<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\LinkPocket.Contracts\LinkPocket.Contracts.csproj" />
    <ProjectReference Include="..\..\src\LinkPocket.Infrastructure\LinkPocket.Infrastructure.csproj" />
  </ItemGroup>
</Project>
