// <auto-generated />
// 本文件由 tools/LinkPocket.ClientGen 从命令描述符机械生成——请勿手改。
// 重新生成：dotnet run --project tools/LinkPocket.ClientGen
#nullable enable
using System.Text.Json;

namespace LinkPocket.Contracts;

/// <summary>引擎客户端便利层：每命令一个强类型直通方法（参数与描述符逐字同源，机械生成）。</summary>
public sealed partial class EngineClient
{

    // —— backup ——

    /// <summary>Export a backup as .lpbackup (format version lpbackup/2.0;SHA-256 manifest + temporary key identity model; temp file in the same directory + atomic replace; trash content is not backed up)</summary>
    public Task<CommandResult<JsonElement>> BackupExportAsync(string outputPath, CallOptions? o = null, CancellationToken ct = default)
        => ExecuteAsync<JsonElement>("backup.export", new { output_path = outputPath }, o, ct);

    /// <summary>Import from a .lpbackup (replace=false appends; replace=true wipes all data first, two-phase confirmation)</summary>
    public Task<CommandResult<JsonElement>> BackupImportAsync(string filePath, bool? replace = null, CallOptions? o = null, CancellationToken ct = default)
        => ExecuteAsync<JsonElement>("backup.import", new { file_path = filePath, replace }, o, ct);

    /// <summary>Read-only inspection of a .lpbackup: version / statistics / integrity result (pre-import assessment, zero side effects)</summary>
    public Task<JsonElement> BackupInspectAsync(string filePath, CallOptions? o = null, CancellationToken ct = default)
        => QueryAsync<JsonElement>("backup.inspect", new { file_path = filePath }, o, ct);

    // —— bookmarks ——

    /// <summary>Export all bookmarks as a Netscape bookmark file (file_path is the target absolute path; unowned bookmarks land at root level so no data is lost)</summary>
    public Task<CommandResult<JsonElement>> BookmarksExportAsync(string filePath, CallOptions? o = null, CancellationToken ct = default)
        => ExecuteAsync<JsonElement>("bookmarks.export", new { file_path = filePath }, o, ct);

    /// <summary>Import all bookmarks and folders from a Netscape bookmark file (appended to existing data; top-level entries land at root level)</summary>
    public Task<CommandResult<JsonElement>> BookmarksImportAsync(string filePath, CallOptions? o = null, CancellationToken ct = default)
        => ExecuteAsync<JsonElement>("bookmarks.import", new { file_path = filePath }, o, ct);

    /// <summary>Read-only preflight of a Netscape bookmark file: format detection, entry statistics, warnings (shared by pre-import display and post-export validation)</summary>
    public Task<BookmarkFileInspectionDto> BookmarksInspectAsync(string filePath, CallOptions? o = null, CancellationToken ct = default)
        => QueryAsync<BookmarkFileInspectionDto>("bookmarks.inspect", new { file_path = filePath }, o, ct);

    // —— dedup ——

    /// <summary>Apply the duplicate handling plan: move the surplus bookmark of each group into the trash per strategy (nested links.trash dispatch, dry_run can rehearse it)</summary>
    public Task<CommandResult<JsonElement>> DedupApplyAsync(string? strategy = null, JsonElement? groupUrls = null, JsonElement? explicitKeep = null, CallOptions? o = null, CancellationToken ct = default)
        => ExecuteAsync<JsonElement>("dedup.apply", new { strategy, group_urls = groupUrls, explicit_keep = explicitKeep }, o, ct);

    // —— favicon ——

    /// <summary>Favicon disk cache statistics (file count, total bytes, cache directory)</summary>
    public Task<JsonElement> FaviconCacheStatsAsync(CallOptions? o = null, CancellationToken ct = default)
        => QueryAsync<JsonElement>("favicon.cache_stats", null, o, ct);

    /// <summary>Queue links with missing favicons for background prefetch (returns immediately; concurrency 4, deduplicated, backoff on failure)</summary>
    public Task<CommandResult<JsonElement>> FaviconPrefetchAsync(IReadOnlyList<string>? linkIds = null, CallOptions? o = null, CancellationToken ct = default)
        => ExecuteAsync<JsonElement>("favicon.prefetch", new { link_ids = linkIds }, o, ct);

    // —— folders ——

    /// <summary>Get the breadcrumb path of a folder (name list, including the root display name)</summary>
    public Task<List<string>> FolderBreadcrumbAsync(string? folderId = null, CallOptions? o = null, CancellationToken ct = default)
        => QueryAsync<List<string>>("folders.breadcrumb", new { folder_id = folderId }, o, ct);

    /// <summary>Get one folder page: direct child folders + direct child links + breadcrumb path (folder_id default = root)</summary>
    public Task<FolderContentsDto> FolderContentsAsync(string? folderId = null, string? sortBy = null, string? sortOrder = null, int? page = null, int? perPage = null, CallOptions? o = null, CancellationToken ct = default)
        => QueryAsync<FolderContentsDto>("folders.contents", new { folder_id = folderId, sort_by = sortBy, sort_order = sortOrder, page, per_page = perPage }, o, ct);

    /// <summary>Deep-copy a folder (including all child folders and bookmarks; returns the new folder ID)</summary>
    public Task<CommandResult<FolderCopyResult>> FolderCopyAsync(string folderId, string? targetParentId = null, CallOptions? o = null, CancellationToken ct = default)
        => ExecuteAsync<FolderCopyResult>("folders.copy", new { folder_id = folderId, target_parent_id = targetParentId }, o, ct);

    /// <summary>Create a folder (optional parent and description; parent_id default = root level)</summary>
    public Task<CommandResult<FolderDto>> FolderCreateAsync(string name, string? description = null, string? parentId = null, CallOptions? o = null, CancellationToken ct = default)
        => ExecuteAsync<FolderDto>("folders.create", new { name, description, parent_id = parentId }, o, ct);

    /// <summary>Check whether moving a folder under the target parent would create a cycle (true = it would)</summary>
    public Task<bool> FolderCycleCheckAsync(string folderId, string? targetParentId = null, CallOptions? o = null, CancellationToken ct = default)
        => QueryAsync<bool>("folders.cycle_check", new { folder_id = folderId, target_parent_id = targetParentId }, o, ct);

    /// <summary>Delete a folder (the whole subtree goes to trash by default; cascade may be delete_all / move_to_list)</summary>
    public Task<CommandResult<FolderDeleteResult>> FolderDeleteAsync(string folderId, string? cascade = null, string? targetListId = null, CallOptions? o = null, CancellationToken ct = default)
        => ExecuteAsync<FolderDeleteResult>("folders.delete", new { folder_id = folderId, cascade, target_list_id = targetListId }, o, ct);

    /// <summary>Find folders by name (exact match by default, optional contains match; used to locate a folder by name)</summary>
    public Task<List<FolderDto>> FolderFindAsync(string name, bool? contains = null, CallOptions? o = null, CancellationToken ct = default)
        => QueryAsync<List<FolderDto>>("folders.find", new { name, contains }, o, ct);

    /// <summary>Get one folder by ID (link_count = recursive link count, direct_link_count = direct child link count)</summary>
    public Task<FolderDto> FolderGetAsync(string? folderId = null, CallOptions? o = null, CancellationToken ct = default)
        => QueryAsync<FolderDto>("folders.get", new { folder_id = folderId }, o, ct);

    /// <summary>Move a folder to a target parent (target_parent_id default = root level)</summary>
    public Task<CommandResult<FolderDto>> FolderMoveAsync(string folderId, string? targetParentId = null, CallOptions? o = null, CancellationToken ct = default)
        => ExecuteAsync<FolderDto>("folders.move", new { folder_id = folderId, target_parent_id = targetParentId }, o, ct);

    /// <summary>Move folders in batch (atomic: any validation failure leaves the whole batch untouched; same names in the target are auto-numbered)</summary>
    public Task<CommandResult<FolderMoveBatchResult>> FolderMoveBatchAsync(IReadOnlyList<string> folderIds, string? targetParentId = null, CallOptions? o = null, CancellationToken ct = default)
        => ExecuteAsync<FolderMoveBatchResult>("folders.move_batch", new { folder_ids = folderIds, target_parent_id = targetParentId }, o, ct);

    /// <summary>A snapshot matching the browser main view: folder page (contents) + full folder tree + root link count (parameters as folders.contents)</summary>
    public Task<FolderContentsDto> FoldersOverviewAsync(string? folderId = null, string? sortBy = null, string? sortOrder = null, int? page = null, int? perPage = null, CallOptions? o = null, CancellationToken ct = default)
        => QueryAsync<FolderContentsDto>("folders.overview", new { folder_id = folderId, sort_by = sortBy, sort_order = sortOrder, page, per_page = perPage }, o, ct);

    /// <summary>Reorder folders under a parent (the order of item_ids is the new order; parent_id default = root level)</summary>
    public Task<CommandResult<FolderSortResult>> FolderSortAsync(IReadOnlyList<string> itemIds, string? parentId = null, CallOptions? o = null, CancellationToken ct = default)
        => ExecuteAsync<FolderSortResult>("folders.sort", new { parent_id = parentId, item_ids = itemIds }, o, ct);

    /// <summary>Get all folders (flat; link_count = recursive link count, direct_link_count = direct child link count, hierarchy assembled by the caller)</summary>
    public Task<List<FolderDto>> FolderTreeAsync(string? sortBy = null, string? sortOrder = null, CallOptions? o = null, CancellationToken ct = default)
        => QueryAsync<List<FolderDto>>("folders.tree", new { sort_by = sortBy, sort_order = sortOrder }, o, ct);

    /// <summary>Update a folder (name and description only; use folders.move to change the parent)</summary>
    public Task<CommandResult<FolderDto>> FolderUpdateAsync(string folderId, string? name = null, string? description = null, CallOptions? o = null, CancellationToken ct = default)
        => ExecuteAsync<FolderDto>("folders.update", new { folder_id = folderId, name, description }, o, ct);

    // —— links ——

    /// <summary>Copy links to a target folder in batch (new links are created; target_list_id default = root level)</summary>
    public Task<CommandResult<LinkBatchResult>> LinkCopyBatchAsync(IReadOnlyList<string> linkIds, string? targetListId = null, CallOptions? o = null, CancellationToken ct = default)
        => ExecuteAsync<LinkBatchResult>("links.copy_batch", new { link_ids = linkIds, target_list_id = targetListId }, o, ct);

    /// <summary>Create a link (list_id default = root level; auto_fetch_metadata optionally fills title/description/favicon)</summary>
    public Task<CommandResult<LinkDto>> LinkCreateAsync(string url, string? title = null, string? description = null, string? listId = null, bool? isImportant = null, bool? autoFetchMetadata = null, string? faviconUrl = null, CallOptions? o = null, CancellationToken ct = default)
        => ExecuteAsync<LinkDto>("links.create", new { url, title, description, list_id = listId, is_important = isImportant, auto_fetch_metadata = autoFetchMetadata, favicon_url = faviconUrl }, o, ct);

    /// <summary>Export all links as a JSON or CSV file (file_path is the target absolute path)</summary>
    public Task<CommandResult<LinkExportResult>> LinkExportAsync(string filePath, string? format = null, CallOptions? o = null, CancellationToken ct = default)
        => ExecuteAsync<LinkExportResult>("links.export", new { file_path = filePath, format }, o, ct);

    /// <summary>Find every link with exactly this URL (reuse point for duplicate handling)</summary>
    public Task<List<LinkDto>> LinkFindByUrlAsync(string url, CallOptions? o = null, CancellationToken ct = default)
        => QueryAsync<List<LinkDto>>("links.find_by_url", new { url }, o, ct);

    /// <summary>Get one link by ID</summary>
    public Task<LinkDto> LinkGetAsync(string id, CallOptions? o = null, CancellationToken ct = default)
        => QueryAsync<LinkDto>("links.get", new { id }, o, ct);

    /// <summary>Paged link query (filter by folder / keyword / important / date; sort_by default created_at, sort_order default desc)</summary>
    public Task<PagedLinksDto> LinkListAsync(string? listId = null, string? search = null, bool? isImportant = null, string? dateFrom = null, string? dateTo = null, string? sortBy = null, string? sortOrder = null, int? page = null, int? perPage = null, CallOptions? o = null, CancellationToken ct = default)
        => QueryAsync<PagedLinksDto>("links.list", new { list_id = listId, search, is_important = isImportant, date_from = dateFrom, date_to = dateTo, sort_by = sortBy, sort_order = sortOrder, page, per_page = perPage }, o, ct);

    /// <summary>Fetch page metadata (title / og: / description / favicon; 10s timeout, runs outside the write gate)</summary>
    public Task<MetadataDto> LinkMetadataFetchAsync(string url, CallOptions? o = null, CancellationToken ct = default)
        => QueryAsync<MetadataDto>("links.metadata_fetch", new { url }, o, ct);

    /// <summary>Move links to a target folder in batch (one atomic transaction; target_list_id default = root level)</summary>
    public Task<CommandResult<LinkBatchResult>> LinkMoveBatchAsync(IReadOnlyList<string> linkIds, string? targetListId = null, CallOptions? o = null, CancellationToken ct = default)
        => ExecuteAsync<LinkBatchResult>("links.move_batch", new { link_ids = linkIds, target_list_id = targetListId }, o, ct);

    /// <summary>Get root-level (unfiled) bookmarks (sort_by default created_at, sort_order default desc; capped at per_page=50)</summary>
    public Task<List<LinkDto>> LinkRootsAsync(string? sortBy = null, string? sortOrder = null, int? perPage = null, CallOptions? o = null, CancellationToken ct = default)
        => QueryAsync<List<LinkDto>>("links.roots", new { sort_by = sortBy, sort_order = sortOrder, per_page = perPage }, o, ct);

    /// <summary>Smart list presets: recently_added | recently_visited | recently_edited | most_visited</summary>
    public Task<List<LinkDto>> LinkSmartListAsync(string kind, int? limit = null, int? days = null, CallOptions? o = null, CancellationToken ct = default)
        => QueryAsync<List<LinkDto>>("links.smart_list", new { kind, limit, days }, o, ct);

    /// <summary>Database statistics: total links / trash item count / root bookmark count / direct child link count per folder</summary>
    public Task<LinkCountsDto> LinkStatsAsync(CallOptions? o = null, CancellationToken ct = default)
        => QueryAsync<LinkCountsDto>("links.stats", null, o, ct);

    /// <summary>Move a link to the trash (soft delete, restorable; the trash keeps the original ID and original-location snapshot)</summary>
    public Task<CommandResult<LinkTrashResult>> LinkTrashAsync(string id, CallOptions? o = null, CancellationToken ct = default)
        => ExecuteAsync<LinkTrashResult>("links.trash", new { id }, o, ct);

    /// <summary>Edit a link (only explicitly provided fields change)</summary>
    public Task<CommandResult<LinkDto>> LinkUpdateAsync(string id, string? url = null, string? title = null, string? description = null, string? listId = null, bool? isImportant = null, string? faviconUrl = null, CallOptions? o = null, CancellationToken ct = default)
        => ExecuteAsync<LinkDto>("links.update", new { id, url, title, description, list_id = listId, is_important = isImportant, favicon_url = faviconUrl }, o, ct);

    /// <summary>Record visits in batch (each link count +1 and last visit refreshed; the folder parent chain is refreshed once per deduplicated folder)</summary>
    public Task<CommandResult<LinkBatchResult>> LinkVisitBatchAsync(IReadOnlyList<string> linkIds, CallOptions? o = null, CancellationToken ct = default)
        => ExecuteAsync<LinkBatchResult>("links.visit_batch", new { link_ids = linkIds }, o, ct);

    /// <summary>Record one visit (link count +1 and last visit refreshed; the folder chain refreshes along the parents)</summary>
    public Task<CommandResult<JsonElement>> LinkVisitRecordAsync(string id, CallOptions? o = null, CancellationToken ct = default)
        => ExecuteAsync<JsonElement>("links.visit_record", new { id }, o, ct);

    // —— locate ——

    /// <summary>Resolve a target location by ID (kind / container folder / path) for locate and jump</summary>
    public Task<LocateResolveDto> LocateResolveAsync(string id, CallOptions? o = null, CancellationToken ct = default)
        => QueryAsync<LocateResolveDto>("locate.resolve", new { id }, o, ct);

    // —— macro ——

    /// <summary>Delete a macro</summary>
    public Task<CommandResult<JsonElement>> MacroDeleteAsync(string name, CallOptions? o = null, CancellationToken ct = default)
        => ExecuteAsync<JsonElement>("macro.delete", new { name }, o, ct);

    /// <summary>Read the batch script definition of a macro</summary>
    public Task<JsonElement> MacroGetAsync(string name, CallOptions? o = null, CancellationToken ct = default)
        => QueryAsync<JsonElement>("macro.get", new { name }, o, ct);

    /// <summary>List all macros (name + updated time, without the script body)</summary>
    public Task<JsonElement> MacroListAsync(CallOptions? o = null, CancellationToken ct = default)
        => QueryAsync<JsonElement>("macro.list", null, o, ct);

    /// <summary>Run a macro with transactional batch semantics (nested step dispatch shares this command's unit of work; abort rolls the whole batch back)</summary>
    public Task<CommandResult<JsonElement>> MacroRunAsync(string name, CallOptions? o = null, CancellationToken ct = default)
        => ExecuteAsync<JsonElement>("macro.run", new { name }, o, ct);

    /// <summary>Save a named batch script (macro / skill library; invalid scripts are rejected)</summary>
    public Task<CommandResult<JsonElement>> MacroSaveRawAsync(string name, JsonElement script, CallOptions? o = null, CancellationToken ct = default)
        => ExecuteAsync<JsonElement>("macro.save", new { name, script }, o, ct);

    // —— maintenance ——

    /// <summary>Collect diagnostics: app version / schema version / per-table counts / cache and event store readings / log and audit readings (redacted)</summary>
    public Task<JsonElement> CollectDiagnosticsAsync(CallOptions? o = null, CancellationToken ct = default)
        => QueryAsync<JsonElement>("diagnostics.collect", null, o, ct);

    /// <summary>Reset the database: wipe all data (links/folders/trash) and clear the favicon cache; unrecoverable, two-phase confirmation required</summary>
    public Task<CommandResult<JsonElement>> MaintenanceReinitAsync(CallOptions? o = null, CancellationToken ct = default)
        => ExecuteAsync<JsonElement>("maintenance.reinit", null, o, ct);

    /// <summary>Get the current database schema version</summary>
    public Task<JsonElement> MaintenanceSchemaVersionAsync(CallOptions? o = null, CancellationToken ct = default)
        => QueryAsync<JsonElement>("maintenance.schema_version", null, o, ct);

    // —— search ——

    /// <summary>Count links matching the search predicate (same scopes as search.links: title/url/description/path)</summary>
    public Task<int> SearchCountAsync(string query, bool? searchTitle = null, bool? searchUrl = null, bool? searchDescription = null, bool? searchPath = null, CallOptions? o = null, CancellationToken ct = default)
        => QueryAsync<int>("search.count", new { query, search_title = searchTitle, search_url = searchUrl, search_description = searchDescription, search_path = searchPath }, o, ct);

    /// <summary>Search links (four scopes: title/url/description/path; default sort title ascending)</summary>
    public Task<List<LinkDto>> SearchLinksAsync(string query, bool? searchTitle = null, bool? searchUrl = null, bool? searchDescription = null, bool? searchPath = null, string? sortBy = null, string? sortOrder = null, int? page = null, int? perPage = null, CallOptions? o = null, CancellationToken ct = default)
        => QueryAsync<List<LinkDto>>("search.links", new { query, search_title = searchTitle, search_url = searchUrl, search_description = searchDescription, search_path = searchPath, sort_by = sortBy, sort_order = sortOrder, page, per_page = perPage }, o, ct);

    // —— staging ——

    /// <summary>List staged files</summary>
    public Task<JsonElement> StagingListAsync(CallOptions? o = null, CancellationToken ct = default)
        => QueryAsync<JsonElement>("staging.list", null, o, ct);

    /// <summary>Copy a file into the AI staging area (registered by SHA-256 fingerprint)</summary>
    public Task<CommandResult<StagedFile>> StageAsync(string sourcePath, CallOptions? o = null, CancellationToken ct = default)
        => ExecuteAsync<StagedFile>("staging.stage", new { source_path = sourcePath }, o, ct);

    /// <summary>Run a pure-function transform pipeline over a staged file (filter_links/rename_folder/map_field/strip_prefix/dedupe/reencode; dry_run returns a preview only)</summary>
    public Task<CommandResult<StagingTransformReport>> StagingTransformAsync(string stagingId, JsonElement ops, bool? dryRun = null, CallOptions? o = null, CancellationToken ct = default)
        => ExecuteAsync<StagingTransformReport>("staging.transform", new { staging_id = stagingId, ops, dry_run = dryRun }, o, ct);

    // —— trash ——

    /// <summary>Flat trash list: individually deleted bookmarks + deleted-folder unit roots (newest deletion first)</summary>
    public Task<List<TrashEntryDto>> TrashListAsync(CallOptions? o = null, CancellationToken ct = default)
        => QueryAsync<List<TrashEntryDto>>("trash.list", null, o, ct);

    /// <summary>A snapshot matching the trash page: all units (subtree counts + original location) + all bookmark snapshots (each carrying its owning unit)</summary>
    public Task<TrashOverviewDto> TrashOverviewAsync(CallOptions? o = null, CancellationToken ct = default)
        => QueryAsync<TrashOverviewDto>("trash.overview", null, o, ct);

    /// <summary>Permanently delete a trash entry (bookmark snapshot or whole unit subtree; unrecoverable, two-phase confirmation)</summary>
    public Task<CommandResult<JsonElement>> TrashPurgeAsync(string id, bool isFolder, CallOptions? o = null, CancellationToken ct = default)
        => ExecuteAsync<JsonElement>("trash.purge", new { id, is_folder = isFolder }, o, ct);

    /// <summary>Permanently delete trash entries in batch (link_ids single snapshots; folder_ids whole unit subtrees; unrecoverable)</summary>
    public Task<CommandResult<TrashPurgeBatchResult>> TrashPurgeBatchAsync(IReadOnlyList<string>? linkIds = null, IReadOnlyList<string>? folderIds = null, CallOptions? o = null, CancellationToken ct = default)
        => ExecuteAsync<TrashPurgeBatchResult>("trash.purge_batch", new { link_ids = linkIds, folder_ids = folderIds }, o, ct);

    /// <summary>Restore a link from the trash (default returns to its pre-deletion folder; when that folder is gone it lands at root and is reported as such)</summary>
    public Task<CommandResult<TrashRestoreResult>> TrashRestoreAsync(string id, string? to = null, CallOptions? o = null, CancellationToken ct = default)
        => ExecuteAsync<TrashRestoreResult>("trash.restore", new { id, to }, o, ct);

    /// <summary>Restore links and units from the trash in batch (mixed; default returns to the pre-deletion location; one atomic transaction)</summary>
    public Task<CommandResult<TrashRestoreBatchResult>> TrashRestoreBatchAsync(IReadOnlyList<string>? linkIds = null, IReadOnlyList<string>? folderIds = null, string? to = null, CallOptions? o = null, CancellationToken ct = default)
        => ExecuteAsync<TrashRestoreBatchResult>("trash.restore_batch", new { link_ids = linkIds, folder_ids = folderIds, to }, o, ct);

    /// <summary>Trash unit tree (flat node list; link_count = bookmarks inside the unit subtree, hierarchy assembled by the caller)</summary>
    public Task<List<TrashFolderDto>> TrashTreeAsync(CallOptions? o = null, CancellationToken ct = default)
        => QueryAsync<List<TrashFolderDto>>("trash.tree", null, o, ct);

    /// <summary>Get trash unit contents: direct child units + all bookmark snapshots in the subtree</summary>
    public Task<List<TrashEntryDto>> TrashUnitContentsAsync(string id, CallOptions? o = null, CancellationToken ct = default)
        => QueryAsync<List<TrashEntryDto>>("trash.unit_contents", new { id }, o, ct);

    // —— undo ——

    /// <summary>Clear the undo and redo stacks</summary>
    public Task<CommandResult<int>> UndoClearAsync(CallOptions? o = null, CancellationToken ct = default)
        => ExecuteAsync<int>("undo.clear", null, o, ct);

    /// <summary>List the undo stack (newest first, capped at 100 entries)</summary>
    public Task<JsonElement> UndoListAsync(CallOptions? o = null, CancellationToken ct = default)
        => QueryAsync<JsonElement>("undo.list", null, o, ct);

    /// <summary>List the redo stack (newest first, capped at 100 entries)</summary>
    public Task<JsonElement> UndoListRedoAsync(CallOptions? o = null, CancellationToken ct = default)
        => QueryAsync<JsonElement>("undo.list_redo", null, o, ct);

    /// <summary>Redo: replay the most recently undone action in forward order (a successful replay re-enters the undo stack)</summary>
    public Task<CommandResult<JsonElement>> RedoAsync(CallOptions? o = null, CancellationToken ct = default)
        => ExecuteAsync<JsonElement>("undo.redo", null, o, ct);
}
