using System.Text;
using System.Text.RegularExpressions;
using LinkPocket.Composition;
using LinkPocket.Contracts;
using LinkPocket.Data;
using LinkPocket.Engine;
using LinkPocket.Kernel;

// EngineClient 便利层生成器
//
// 用法：dotnet run --project tools/LinkPocket.ClientGen [--check]
//   缺省写 src/LinkPocket.Contracts/Engine/EngineClient.Generated.cs
//   --check  只校验"现有生成文件与当前命令描述符一致"，不写盘；不一致退出码 2（CI 门禁用）
//
// 为什么需要它：EngineClient 的几十个便利方法只是"每命令一个强类型直通"，
// 参数名/类型/顺序全部派生自命令描述符。手工维护 = 描述符一改就得人工跟改签名（漂移）。
// 这里从组装好的引擎目录读出描述符（含 Client 绑定），机械生成整层；
// 唯一机器读不到的"方法名 + 返回载荷类型"由描述符的 ClientBinding 声明。
//
// 为什么不连数据库：生成只需要命令注册表 + 描述符。工作单元/宏库工厂都给"调用即抛"的占位，
// 一旦有人误在这里触库会立刻炸，而不是悄悄建出一个库文件。

var repoRoot = FindRepoRoot();
var target = Path.Combine(repoRoot, "src", "LinkPocket.Contracts", "Engine", "EngineClient.Generated.cs");
var checkOnly = args.Contains("--check", StringComparer.Ordinal);

var composed = EngineComposer.Compose(NoDatabase, NoDatabaseContext, new ComposeOptions
{
    SqlAudit = false,
    BuildWire = false,
    StagingRoot = Path.Combine(TempArea.Resolve(), "linkpocket-clientgen-staging"),
});

var catalog = OrchestrationHost.CreateCatalog(composed.Registry);
var text = ClientGenerator.Generate(catalog.Manifest(), out var generatedCount);

if (checkOnly)
{
    var existing = File.Exists(target) ? File.ReadAllText(target) : null;
    if (existing is null || Normalize(existing) != Normalize(text))
    {
        Console.Error.WriteLine(
            "EngineClient.Generated.cs 与命令描述符不一致（请运行 tools/LinkPocket.ClientGen 重新生成）。");
        return 2;
    }

    Console.WriteLine($"EngineClient.Generated.cs 与命令描述符一致（{generatedCount} 个便利方法）。");
    return 0;
}

File.WriteAllText(target, text, new UTF8Encoding(false));
Console.WriteLine($"已生成 {target}（{generatedCount} 个便利方法）。");
return 0;

// —— 不触碰数据库的占位实现：生成流程里任何真实数据访问都是缺陷，要立刻暴露 ——

static IUnitOfWork NoDatabase()
    => throw new InvalidOperationException("便利层生成不需要数据库：请勿在生成流程中执行业务命令。");

static LinkPocketDbContext NoDatabaseContext()
    => throw new InvalidOperationException("便利层生成不需要数据库：请勿在生成流程中读取宏库。");

/// <summary>从当前目录向上回溯到含 LinkPocket.sln 的仓库根（脚本与 IDE 两种启动方式都成立）。</summary>
static string FindRepoRoot()
{
    var dir = new DirectoryInfo(AppContext.BaseDirectory);
    while (dir is not null && !File.Exists(Path.Combine(dir.FullName, "LinkPocket.sln")))
        dir = dir.Parent;
    return dir?.FullName ?? Directory.GetCurrentDirectory();
}

static string Normalize(string content) => content.Replace("\r\n", "\n");

/// <summary>从命令描述符机械生成便利层源码（唯一事实源 = 描述符 + ClientBinding）。</summary>
internal static class ClientGenerator
{
    private static readonly Regex TypeWords = new(
        @"\b(String|Boolean|Int32|Int64|Int16|UInt32|UInt64|Double|Single|Decimal|Byte|SByte|Char|Object)\b",
        RegexOptions.Compiled);

    public static string Generate(EngineManifest manifest, out int count)
    {
        var commands = manifest.Commands
            .Where(c => c.Client is not null)
            .OrderBy(c => c.Category, StringComparer.Ordinal)
            .ThenBy(c => c.Name, StringComparer.Ordinal)
            .ToArray();
        count = commands.Length;

        var sb = new StringBuilder();
        sb.Append("// <auto-generated />\n");
        sb.Append("// 本文件由 tools/LinkPocket.ClientGen 从命令描述符机械生成——请勿手改。\n");
        sb.Append("// 重新生成：dotnet run --project tools/LinkPocket.ClientGen\n");
        sb.Append("#nullable enable\n");
        sb.Append("using System.Text.Json;\n\n");
        sb.Append("namespace LinkPocket.Contracts;\n\n");
        sb.Append("/// <summary>引擎客户端便利层：每命令一个强类型直通方法（参数与描述符逐字同源，机械生成）。</summary>\n");
        sb.Append("public sealed partial class EngineClient\n{\n");

        string? category = null;
        foreach (var command in commands)
        {
            if (!string.Equals(command.Category, category, StringComparison.Ordinal))
            {
                category = command.Category;
                sb.Append($"\n    // —— {category} ——\n");
            }

            sb.Append(Emit(command));
        }

        sb.Append("}\n");
        return sb.ToString();
    }

    private static string Emit(CommandDescriptor command)
    {
        var payload = FriendlyName(command.Client!.Result);
        var returns = command.IsQuery ? payload : $"CommandResult<{payload}>";
        var flow = command.IsQuery ? "Query" : "Execute";

        var orderedParams = command.Parameters
            .OrderByDescending(p => p.Required)   // 必填必须排在可选之前（C# 语法约束；稳定排序保持原有相对次序）
            .ToArray();

        var parameters = orderedParams.Select(p =>
        {
            var ident = Camel(p.Name);
            var type = CsType(p.TypeName, optional: !p.Required);
            var @default = p.Required ? string.Empty : " = null";
            return $"{type} {ident}{@default}";
        }).ToList();
        parameters.Add("CallOptions? o = null");
        parameters.Add("CancellationToken ct = default");

        var args = command.Parameters.Count == 0
            ? "null"
            : "new { " + string.Join(", ", command.Parameters.Select(p =>
            {
                var ident = Camel(p.Name);
                return string.Equals(ident, p.Name, StringComparison.Ordinal) ? ident : $"{p.Name} = {ident}";
            })) + " }";

        var sb = new StringBuilder();
        sb.Append($"\n    /// <summary>{Doc(command.Description)}</summary>\n");
        sb.Append($"    public Task<{returns}> {command.Client!.Method}({string.Join(", ", parameters)})\n");
        sb.Append($"        => {flow}Async<{payload}>(\"{command.Name}\", {args}, o, ct);\n");
        return sb.ToString();
    }

    /// <summary>描述符参数名（snake_case）→ C# 标识符（camelCase）。</summary>
    private static string Camel(string snake)
    {
        var parts = snake.Split('_', StringSplitOptions.RemoveEmptyEntries);
        if (parts.Length == 0) return snake;
        var sb = new StringBuilder(parts[0]);
        for (var i = 1; i < parts.Length; i++)
            sb.Append(char.ToUpperInvariant(parts[i][0])).Append(parts[i][1..]);
        return sb.ToString();
    }

    /// <summary>描述符类型名（.NET 名，如 <c>Int32</c>/<c>IReadOnlyList&lt;String&gt;</c>）→ C# 类型语法。</summary>
    private static string CsType(string typeName, bool optional)
    {
        var type = MapWords(typeName);
        if (optional && !type.EndsWith('?')) type += "?";
        return type;
    }

    private static string MapWords(string name) => TypeWords.Replace(name, m => m.Value switch
    {
        "String" => "string",
        "Boolean" => "bool",
        "Int32" => "int",
        "Int64" => "long",
        "Int16" => "short",
        "UInt32" => "uint",
        "UInt64" => "ulong",
        "Double" => "double",
        "Single" => "float",
        "Decimal" => "decimal",
        "Byte" => "byte",
        "SByte" => "sbyte",
        "Char" => "char",
        "Object" => "object",
        _ => m.Value,
    });

    private static string FriendlyName(Type type)
    {
        var underlying = Nullable.GetUnderlyingType(type);
        if (underlying is not null) return FriendlyName(underlying);
        if (type.IsArray) return FriendlyName(type.GetElementType()!) + "[]";
        if (type.IsGenericType)
        {
            var bare = type.Name[..type.Name.IndexOf('`')];
            return $"{bare}<{string.Join(", ", type.GetGenericArguments().Select(FriendlyName))}>";
        }

        return MapWords(type.Name);
    }

    /// <summary>XML 文档转义：转义 <c>&amp; &lt; &gt;</c>，并把非法的 <c>--</c> 拆开。</summary>
    private static string Doc(string text)
        => text.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;").Replace("--", "- -");
}
